# Generated by Django 4.1.5 on 2023-01-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addtasks',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=500)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Status', models.IntegerField(choices=[(1, 'In progress'), (2, 'Pending'), (3, 'Done')], default=1)),
                ('RequestNumber', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assigntasks',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=500)),
                ('Pic', models.CharField(max_length=500)),
            ],
        ),
    ]
