# Generated by Django 4.1.5 on 2023-01-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddtaskApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addtasks',
        ),
        migrations.DeleteModel(
            name='Assigntasks',
        ),
    ]
