# Generated by Django 4.1.5 on 2023-01-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddtaskApp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tasks',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
