# Generated by Django 4.1.5 on 2023-01-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AddtaskApp', '0004_delete_tasks_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=40)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'done'), (1, 'pending'), (2, 'Not target')], default=2)),
                ('teamPic', models.IntegerField(null=True)),
            ],
        ),
    ]
