# Generated by Django 4.1.5 on 2023-01-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddtaskApp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='numberofrequest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='teamPic',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
