# Generated by Django 4.1.5 on 2023-01-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddtaskApp', '0006_tasks_numberofrequest_alter_tasks_teampic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='taskname',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='numberofrequest',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='teamPic',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('role', models.IntegerField(choices=[(0, 'admin'), (1, 'lead'), (2, 'user')], default=2)),
                ('request', models.IntegerField(default=0)),
                ('team', models.ForeignKey(db_column='teamPic', on_delete=django.db.models.deletion.CASCADE, related_name='pic', to='AddtaskApp.tasks')),
            ],
        ),
    ]
