# Generated by Django 4.1.5 on 2023-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddtaskApp', '0007_rename_taskname_tasks_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='numberofrequest',
            field=models.IntegerField(null=True),
        ),
    ]
